const fs = require('fs');
const path = require('path');

const RAW_DIR = path.join(__dirname, '../src/assets/raw');
const OUTPUT_FILE = path.join(__dirname, '../src/assets/image_data.js');

console.log("Compiling assets...");

if (!fs.existsSync(RAW_DIR)) {
    console.log("No raw assets directory found.");
    process.exit(0);
}

const files = fs.readdirSync(RAW_DIR);
const assets = {};

files.forEach(file => {
    if (file.endsWith('.png') || file.endsWith('.jpg')) {
        const name = path.parse(file).name;
        const filePath = path.join(RAW_DIR, file);
        const data = fs.readFileSync(filePath);
        const base64 = data.toString('base64');
        const mime = file.endsWith('.png') ? 'image/png' : 'image/jpeg';

        assets[name] = `data:${mime};base64,${base64}`;
        console.log(`  Packed ${name}`);
    }
});

const content = `/**
 * ASSET DATA
 * Auto-generated by tools/convert_assets.js
 */
const ASSET_DATA = ${JSON.stringify(assets, null, 4)};
`;

fs.writeFileSync(OUTPUT_FILE, content);
console.log(`Saved to ${OUTPUT_FILE}`);
